### ISSUE TITLE
Breaking change use of svelte internal with Svelte 5 

### ISSUE THREAD

**Issue by barcovanrhijn** [jjagielka/svelte-pivottable#2]
I've imported svelte-pivottable into a new Svelte 5 project. The project fails to build because of the use of svelte internal in velte-pivottable. The issue will affect all new installs of Svelte.

```
 node_modules/svelte-pivottable/UI/DraggableAttribute.svelte (4:13): "is_empty" is not exported by "node_modules/svelte/src/internal/index.js", imported by "node_modules/svelte-pivottable/UI/DraggableAttribute.svelte".


DraggableAttribute.svelte:4:13
    4:     import { is_empty } from "svelte/internal";
    
    export let valueFilter;

        at getRollupError (file:///home/barco/workspace/goodxweb/build/subapps/report/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
        at error (file:///home/barco/workspace/goodxweb/build/subapps/report/node_modules/rollup/dist/es/shared/parseAst.js:392:42)
        at Module.error (file:///home/barco/workspace/goodxweb/build/subapps/report/node_modules/rollup/dist/es/shared/node-entry.js:15590:16)
        at Module.traceVariable (file:///home/barco/workspace/goodxweb/build/subapps/report/node_modules/rollup/dist/es/shared/node-entry.js:16039:29)
        at ModuleScope.findVariable (file:///home/barco/workspace/goodxweb/build/subapps/report/node_modules/rollup/dist/es/shared/node-entry.js:13822:39)
        at FunctionScope.findVariable (file:///home/barco/workspace/goodxweb/build/subapps/report/node_modules/rollup/dist/es/shared/node-entry.js:5285:38)
        at FunctionBodyScope.findVariable (file:///home/barco/workspace/goodxweb/build/subapps/report/node_modules/rollup/dist/es/shared/node-entry.js:5285:38)
        at Identifier.bind (file:///home/barco/workspace/goodxweb/build/subapps/report/node_modules/rollup/dist/es/shared/node-entry.js:5068:40)
        at CallExpression.bind (file:///home/barco/workspace/goodxweb/build/subapps/report/node_modules/rollup/dist/es/shared/node-entry.js:2655:23)
        at CallExpression.bind (file:///home/barco/workspace/goodxweb/build/subapps/report/node_modules/rollup/dist/es/shared/node-entry.js:11286:15)
    make: * [Makefile:4: build] Error 1
     Use --force to continue.

    Aborted due to warnings.

```

In Browser errors mentions that using svelte/internal should not usually be used. But calls for authors to reach out to Svelte via an issue if this usage is a legitimate use case.

**Comment by barcovanrhijn** [comment]
See https://github.com/jjagielka/svelte-pivottable/pull/3

**Comment by jjagielka** [comment]
PR #1 merged.
